export interface EnvOptions {
  port: number;
  includeDb: boolean;
  dbConnectionString?: string;
  dbPassword: string;
  screenshotsPath: string;
}

export function generateEnv(options: EnvOptions): string {
  const lines: string[] = [];

  lines.push("# Argus Web Dashboard Configuration");
  lines.push("# Generated by argus-web init");
  lines.push("");

  lines.push("# Server port");
  lines.push(`PORT=${options.port}`);
  lines.push("");

  if (options.includeDb) {
    lines.push("# Database password (used by both PostgreSQL container and web app)");
    lines.push(`DB_PASSWORD=${options.dbPassword}`);
  } else {
    lines.push("# PostgreSQL connection string");
    lines.push(`DATABASE_URL=${options.dbConnectionString || "postgresql://user:password@host:5432/argus"}`);
  }
  lines.push("");

  lines.push("# Path to screenshots directory (mounted read-only into the container)");
  lines.push(`SCREENSHOTS_PATH=${options.screenshotsPath}`);
  lines.push("");

  return lines.join("\n");
}
