export interface EnvOptions {
  port: number;
  includeDb: boolean;
  dbConnectionString?: string;
  dbPassword: string;
  screenshotsPath: string;
  githubClientId: string;
  githubClientSecret: string;
  sessionSecret: string;
  apiKey: string;
}

export function generateEnv(options: EnvOptions): string {
  const lines: string[] = [];

  lines.push("# Argus Web Dashboard Configuration");
  lines.push("# Generated by argus-web init");
  lines.push("");

  lines.push("# Server port");
  lines.push(`PORT=${options.port}`);
  lines.push("");

  if (options.includeDb) {
    lines.push("# Database password (used by both PostgreSQL container and web app)");
    lines.push(`DB_PASSWORD=${options.dbPassword}`);
  } else {
    lines.push("# PostgreSQL connection string");
    lines.push(`DATABASE_URL=${options.dbConnectionString || "postgresql://user:password@host:5432/argus"}`);
  }
  lines.push("");

  lines.push("# Path to screenshots directory (mounted read-only into the container)");
  lines.push(`SCREENSHOTS_PATH=${options.screenshotsPath}`);
  lines.push("");

  lines.push("# GitHub OAuth (create app at https://github.com/settings/developers)");
  lines.push(`GITHUB_CLIENT_ID=${options.githubClientId}`);
  lines.push(`GITHUB_CLIENT_SECRET=${options.githubClientSecret}`);
  lines.push("");

  lines.push("# Session encryption key (auto-generated)");
  lines.push(`SESSION_SECRET=${options.sessionSecret}`);
  lines.push("");

  lines.push("# API key for CI/CD uploads (Authorization: Bearer <key>)");
  lines.push(`ARGUS_API_KEY=${options.apiKey}`);
  lines.push("");

  return lines.join("\n");
}
