/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as BranchesIndexRouteImport } from './routes/branches/index'
import { Route as TestsIdRouteImport } from './routes/tests/$id'
import { Route as BranchesNameRouteImport } from './routes/branches/$name'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdRoute = TestsIdRouteImport.update({
  id: '/tests/$id',
  path: '/tests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesNameRoute = BranchesNameRouteImport.update({
  id: '/branches/$name',
  path: '/branches/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/branches/$name': typeof BranchesNameRoute
  '/tests/$id': typeof TestsIdRoute
  '/branches/': typeof BranchesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/branches/$name': typeof BranchesNameRoute
  '/tests/$id': typeof TestsIdRoute
  '/branches': typeof BranchesIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/branches/$name': typeof BranchesNameRoute
  '/tests/$id': typeof TestsIdRoute
  '/branches/': typeof BranchesIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upload'
    | '/branches/$name'
    | '/tests/$id'
    | '/branches/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/branches/$name'
    | '/tests/$id'
    | '/branches'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/upload'
    | '/branches/$name'
    | '/tests/$id'
    | '/branches/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadRoute: typeof UploadRoute
  BranchesNameRoute: typeof BranchesNameRoute
  TestsIdRoute: typeof TestsIdRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$id': {
      id: '/tests/$id'
      path: '/tests/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof TestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$name': {
      id: '/branches/$name'
      path: '/branches/$name'
      fullPath: '/branches/$name'
      preLoaderRoute: typeof BranchesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRoute: UploadRoute,
  BranchesNameRoute: BranchesNameRoute,
  TestsIdRoute: TestsIdRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
